Document: gasfinder
Title: Debian gasfinder Manual
Author: <insert document author here>
Abstract: This manual describes what gasfinder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gasfinder/gasfinder.sgml.gz

Format: postscript
Files: /usr/share/doc/gasfinder/gasfinder.ps.gz

Format: text
Files: /usr/share/doc/gasfinder/gasfinder.text.gz

Format: HTML
Index: /usr/share/doc/gasfinder/html/index.html
Files: /usr/share/doc/gasfinder/html/*.html
